<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 2.11.11.1 setup script by Michal Čihař <michal@cihar.com>
 * Version: $Id$
 * Date: Sat, 08 Jan 2011 18:53:28 GMT
 */

/* Servers configuration */
$i = 0;

/* Server Main (http) [1] */
$i++;
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['verbose'] = 'Main HTTP';

$cfg['Servers'][$i]['AllowDeny']['order'] = '';

$cfg['Servers'][$i]['AllowDeny']['rules'] = array();



/* End of servers configuration */

?>
